spring.application.name=users-service

spring.datasource.url=jdbc:postgresql://localhost:5432/gateway_auth
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop

server.port=0

# spring cloud configs
#spring.main.web-application-type=reactive
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/